### ISSUE TITLE
opentok-whiteboard doesn't have a undo-redo function?

### ISSUE THREAD

**Issue by sumansaurabh** [aullman/opentok-whiteboard#12]
Can this functionality be committed to the opentok-whiteboard, I have already added this functionality to my cloned repo.

**Comment by aullman** [comment]
Sure, can you submit a pull request?

**Comment by sumansaurabh** [comment]
1) Added Undo Redo Functionality, also supports mobile devices.
2) Added javascript confirmation box on clearing whiteboard as undo/redo is impossible after clearing Whiteboard.
