### ISSUE TITLE
Archive whiteboard sessions

### ISSUE THREAD

**Issue by Yugandharjaiswal** [aullman/opentok-whiteboard#25]
Hello, can i store whiteboard archives like what i can do with the video
can i also store whiteboard session so that i can replay that in future
and BTW .... really appriciate the work you did with tokbox
i really needed this whiteboard in my project thanx

**Comment by aullman** [comment]
There are a few options here I can think of.

1. You can save the whiteboard image with the capture button. 
2. You could screenshare it using opentok and archive the screenshare
3. You could store a timeline of the signals that are sent and play them back for the whiteboard
4. You could use the [MediaRecorder](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder) and [Canvas.captureStream](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream) APIs in the browser to create a video file from the Whiteboard Canvas.
